## Ejercicio 1 

En data science y programación científica es común necesitar vectores con valores dentro de cierto intervalo, pero con sub-intervalos internos con diference espaciamiento ,por ejemplo:

[0.  , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.7 , 0.8 , 0.9 , 1.  ]
       
El primer sub-intervalo incrementa de 0.1 en 0.1 , el segundo de 0.01 en 0.01 , y el tercero de 0.1 en 0.1 nuevamente.

Usando unicamente NumPy crea un vector de este tipo con el nombre xs .

**nota**: no es permitido usar ciclos, debe realizarse con operaciones "vectorizadas" de numpy

In [1]:
import numpy as np

In [3]:
x=np.linspace(0,0.4,5)
y=np.linspace(0.5,0.6,11)
z=np.linspace(0.7,1,4)
xs=np.hstack((x,y,z))
xs

array([0.  , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.7 , 0.8 , 0.9 , 1.  ])

## Ejercicio 2
En este caso usamos un ciclo  para ejemplificar pero ya hemos mencionado que debemos evitarlos siempre que sea posible y usar operaciones "vectorizadas" ya que es mucho mas rápido al utilizar  código pre-compilado de C, en este ejercicio debemos remplazar el calculo de xs para hacerlo de manera "vectorizada" y eliminar el ciclo for. 

**tip**: usar slicing

### Ejemplo usando ciclos

In [4]:
# las siguientes 3 lineas generan un conjunto de datos que se comportan segun una onda senoidal pero tienen
# ruido por lo cual vamos a suavizar usando promedio de 3 puntos
# en este ejercicio los generamos manualmente pero pensemos que son datos que pudieron ser generados con algún
# instrumento como un sensor, o bien estar almacenados en una base de datos
sample_points= 1000
ruido = 0.1*np.random.randn(sample_points) #el ruido comunmente se debe a aleatoriedad o captura no exacta de info.
x = np.linspace(0,2*np.pi,sample_points)
y = np.sin(x) + ruido

#xs es "x suavizado", inicialmente es una copia de x
ys =  y.copy()

for n in range(1,len(y)-1):
    ys[n] = (y[n-1] + y[n] + y[n+1])/3
    
print(y)
print(ys)

[ 3.71666843e-02 -4.95734735e-03 -1.29916798e-01 -9.25777450e-02
 -6.64975009e-03  7.90285049e-02  3.32102533e-02  9.86877820e-03
  2.10072039e-01  2.84642411e-01  1.73319370e-01  1.21809816e-01
  7.17950141e-02  1.20603148e-01  1.40737372e-01  1.81208495e-01
  7.63359154e-02  1.68969701e-01  1.45989711e-01  9.39372402e-03
  1.90194454e-01  1.86621136e-01  1.60670490e-01  1.42971869e-01
  6.74835291e-02  1.45643475e-01  8.11912249e-02  1.31110398e-01
  2.16754723e-01  2.34692656e-01  1.49271479e-01  3.55257754e-01
  3.98534006e-02  1.87523230e-01  8.77717029e-02 -4.11213084e-02
  1.54510327e-01  1.29083028e-01  3.46632194e-01  2.94228219e-01
  4.08920475e-01  2.05265904e-01  2.55653875e-01  1.03027785e-01
  1.10074880e-01  3.29568622e-01  4.38163162e-01  2.07301589e-01
  1.95842871e-01  2.53152777e-01  2.53164976e-01  2.39769581e-01
  2.44333681e-01  3.86303840e-01  3.35025866e-01  1.77194415e-01
  2.72330760e-01  5.32783002e-01  2.76323941e-02  2.52497368e-01
  4.09334579e-01  3.06966

### Ejemplo usando funciones de numphy

In [13]:
# Asignar valores a ys usando numphy
yp=np.hstack((y[1:len(y)],np.nan))
yz=np.hstack((np.nan,y[:len(y)-1]))
ys=(yp+y+yz)/3

# Agregar valores a los extremos
ys[0]=y[0]
ys[len(ys)-1]=y[len(y)-1]

print(ys)

[ 3.71666843e-02 -3.25691536e-02 -7.58172967e-02 -7.63814310e-02
 -6.73299676e-03  3.51963360e-02  4.07025121e-02  8.43836902e-02
  1.68194409e-01  2.22677940e-01  1.93257199e-01  1.22308067e-01
  1.04735993e-01  1.11045178e-01  1.47516338e-01  1.32760594e-01
  1.42171371e-01  1.30431776e-01  1.08117712e-01  1.15192629e-01
  1.28736438e-01  1.79162027e-01  1.63421165e-01  1.23708629e-01
  1.18699625e-01  9.81060765e-02  1.19315033e-01  1.43018782e-01
  1.94185926e-01  2.00239619e-01  2.46407296e-01  1.81460878e-01
  1.94211462e-01  1.05049444e-01  7.80578748e-02  6.70535739e-02
  8.08240158e-02  2.10075183e-01  2.56647814e-01  3.49926963e-01
  3.02804866e-01  2.89946751e-01  1.87982521e-01  1.56252180e-01
  1.80890429e-01  2.92602221e-01  3.25011124e-01  2.80435874e-01
  2.18765746e-01  2.34053541e-01  2.48695778e-01  2.45756079e-01
  2.90135701e-01  3.21887796e-01  2.99508040e-01  2.61517014e-01
  3.27436059e-01  2.77582052e-01  2.70970921e-01  2.29821447e-01
  3.22932775e-01  3.46064

## Ejercicio 3: Entropía
Para calcular la información de una distribución de probabilidad necesitamos calcular el producto entre la información de cada posible x y su probabilidad , cada uno de estos elementos nos indica cuanta incerteza aporta cada x a la entropía de la distribución. Crea una función que calcule esto, debe recibir un vector representando a la dist. de probabilidad y devoler otro vector con el termino de entropía para cada x. Por ejemplo:

calcular_entropia([0.25,0.75])

Debe resultar en :

[0.5    ,    0.31127812]

**Nota**: la entropía es la suma sobre estos valores, en este caso no calculamos la entropía,unicamente los termimos de su sumatoria. La entropía es:

$$S = -\sum_i^nP(x_{i})log_{2}P(x_{i})$$

In [15]:
# Funcion Px proporcionada en clase
def calcular_informacion(px):
    return np.log2(px)*-1

distribucion_prob1 = [1.0]
distribucion_prob2 = [0.5,0.5] #La entropía es máxima cuando todos los eventos tienen la misma probabilidad.
distribucion_prob3 = [1.0,0.0]
distribucion_prob4 = [0.9999]
distribucion_prob5 = [0.25,0.75]
distribucion_prob6 = [0.2]*5 # ojo estas son listas por lo tanto * la replica, no son arrays de numpy
distribucion_prob7 = [0.4,0.2,0.1,0.1,0.2]

print(calcular_informacion(distribucion_prob1))
print(calcular_informacion(distribucion_prob2))
print(calcular_informacion(distribucion_prob3))
print(calcular_informacion(distribucion_prob4))
print(calcular_informacion(distribucion_prob5))
print(calcular_informacion(distribucion_prob6))
print(calcular_informacion(distribucion_prob7))

[-0.]
[1. 1.]
[-0. inf]
[0.00014428]
[2.        0.4150375]
[2.32192809 2.32192809 2.32192809 2.32192809 2.32192809]
[1.32192809 2.32192809 3.32192809 3.32192809 2.32192809]


C:\Users\ruben\AppData\Local\Continuum\anaconda3\envs\Galileo-Python\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log2
  


In [19]:
# Funcion del calculo de la entropia solicitada para el ejercicio
def calcular_entropia(x):
    px=calcular_informacion(x)
    return x*px
print(calcular_entropia([0.25,0.75]))

[0.5        0.31127812]


## Ejercicio 4: Cálculo de costos
Se ha determinado también que hay costos asociados a la comunicación y relación con los clientes(llamadas,mensajes electrónicos,etc) y que estos también tienen alta correlación con el monto que estos gastan en su primer més siguiendo el modelo:
$$c(x) = (x^{2} + x + log (0.0001x)-\sqrt{0.54x})/100$$

Cree una función para calcular este modelo sobre valores de de gasto de nuevos clientes , y luego cree una función  **ganancia_neta(x,g,c)** donde:
* x = vector conteniendo los valores de gasto del primer mes para nuevos clientes.
* g = función que estima la ganancia en función de x
* c = función que estima el costo en función de x

La función realiza el calculo simple **g(x) - c(x)** , ya que es posible que los modelos cambien en el tiempo es común recibir como parámetro el modelo o modelos hijos de un modelo mas grande , en este caso eso se logra recibiendo como parámetro las funciones de ganancia y costo.

In [24]:
# Funcion proporcionada por el ejercicio
def g(x):
    ganancia = (np.power(x,3) + 2.0*(np.power(x,2.0))+np.exp(0.0001*x) - np.sqrt(2.0*x))/50
    
    return ganancia
    
gastos = np.array([100,50,25])
ganancia = g(gastos)

print("Ganancias",ganancia)

Ganancias [20399.73735829  2599.82010025   337.37862871]


In [23]:
def c(x):
    costos = (np.power(x,2) + x +np.log(0.0001*x) - np.sqrt(0.54*x))/100
    return costos

def ganancia_neta(a,fun_g,fun_c):
    return fun_g(a)-fun_c(a)

setdeValores = np.array([100,50,25])
utilidad_bruta = ganancia_neta(setdeValores,g,c)

print("Ganancia Neta: ",utilidad_bruta)

Ganancias [20298.85689469  2574.42504495   330.9752857 ]


## Ejercicio 5: Calcular la moda de un vector x
Usando argmax crear una función mode(x) para calcular la moda de un vector x , esta función debe devolver una tupla de 2 elementos de la forma:

(valor,conteo)

**tip** investigar y auxiliarse de otras funciones de numpy y np.argmax, no olvidar trabajar todo vectorizado, sin ciclos.

In [59]:
def mode(x):
    ## tu codigo aqui (~ 3 lineas de codigo):
    (unicos,veces) = np.unique(x, return_counts=True)
    posmaxrepetido=np.argmax(veces)
    return unicos[posmaxrepetido], veces[posmaxrepetido]
prueba=np.array([1,4,4,3,5])
#max(set (a), key=lambda x: a.count(x))
print(mode(prueba))

(4, 2)


## Ejercicio 6: Calculo de la entropia
Crear una función para calcular la entropía  de una distribución de probabilidad representada como un vector.
$$S = -\sum_i^nP(x_{i})log_{2}P(x_{i})$$

**Nota**: a diferencia del ejercicio anterior donde solo calculamos los términos de la entropía, en este caso  si calculamos el valor completo de la entropía, que como mencionamos es una medida de incerteza en una distribución de probabilidad.

**recordatorio**: no usar ciclos solo operaciones vectorizadas.

In [61]:
def calculoS_entropia(x):
    return -np.sum(x)
print(calculoS_entropia(calcular_entropia([0.25,0.75])))

-0.8112781244591328


## Ejercicio 7: Entropia cruzada
En ML usamos la entropía cruzada como una forma de medir que tan bueno es un modelo de variables discretas a través de comparar la distribución de probabilidad que el modelo produce o predice, vs la distribución de probabilidad real dada por los datos de entrenamiento.

Podemos ver el siguiente ejemplo que define la forma en que se calcula la entropía cruzada y nos muestra un caso específico:

<img src="https://image.slidesharecdn.com/publishintroductiontodeeplearninginpythonandmatlab1-160502102437/95/introduction-to-deep-learning-in-python-and-matlab-54-638.jpg?cb=1462185644">

En este caso interpretamos así: El problema consiste en un modelo o algoritmo de ML que debe producir un vector de 3 elementos indicando la probabilidad de que ciertos datos X pertenezcan a una de 3 categorías.

* El modelo de ML produce un vector que indica que estima un 70% de probabilidad de que se trate de la categoría 0, 20% de probabilidad de que se trate de la categoría 1 y 10% de que se trate de la categoría 2.
* Los datos reales nos dicen que se trataba de un caso donde con total certeza se sabe que se trata de la categoría 0
* La entropía cruzada(a calcular en el ejercicio) nos indica que tan buena es la estimación del modelo, una EC de 0 es un modelo perfecto(en este caso un modelo que predice 100% de prob para la clase 0)

**Nota** 
* Aun que para calcular la entropía usamos logaritmos en base 2, en ML para calcular la entropía cruzada se usa logaritmo natural ya que con este se cumple el proposito **estimar que tanto se alejan las predicciones del modelo de ML de los datos reales** y es comunmente mas rápido de calcular en la computadora.
* Ya que estamos trabajando con vectores que representan distribuciones de probabilidad , podemos toparnos con lo que se conoce como : **sparse vectors**(vectores donde la mayoría de elementos son 0), esto puede producir problemas ya que le logaritmo de 0 no esta definido, tu solución debe tomar en cuenta esto y evitar que devuelva "nan"

In [68]:
def cross_entropy(Y,Y_hat):
    ##tu codigo aqui (~ 1 lineas de codigo)
    return -np.sum(Y*np.log(Y_hat))
    
    
    

y  = np.array([1.0,0,0])
y_hat = np.array([0.7,0.2,0.1])

cross_entropy(y,y_hat)

0.35667494393873245

## Ejercicio 8: Norma de un vector
Crear una función que reciba como parámetro un vector x y calcule su magnitud o norma(euclidiana o L2) ,luego usarla para evaluar 2 vectores que representan los errores generados por 2 modelos de machine learning y concluir cual de los 2 modelos es mejor.

In [69]:
def magnitud(x):
    ## tu codigo aqui (~ 1 linea de codigo)
    return np.sqrt(np.sum(np.power(x,2)))

errores_modelo1 = np.array([1,2,1,2])
errores_modelo2 = np.array([0,1,1,2])

print(magnitud(errores_modelo1))
print(magnitud(errores_modelo2))

3.1622776601683795
2.449489742783178


## Ejercicio 9: Normalizacion de vectores
Usando la función del ejercicio anterior, crea otra función normalizar(x) que reciba de parámetro un vector x aplique normalización sobre este, el resultado debe ser un nuevo vector del tamaño de x cuya magnitud es igual a 1.0

In [70]:
def normalizar(x):
    ## tu codigo aqui (~ 3 linea de codigo)
    return x/magnitud(x)
    

print(magnitud(normalizar(errores_modelo1)))
print(normalizar(errores_modelo2))

1.0
[0.         0.40824829 0.40824829 0.81649658]


## Ejercicio 10: Red Neuronal

Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Asumiendo que cada neurona identifica la similitud entre su entrada y la caracteística que representa concluir:
* Para cada vector de entrada Xi , cual neurona intermedia busca la característica que mas se parece a X.
* Cual vector de entrada Xi produce una activación alta(salida alta) en la capa de salida.

In [72]:
# Aplicar la red neuronal sobre los siguientes datos X

X1 = np.array([0.50,0.72])
X2 = np.array([-4,7])
X3 = np.zeros_like(X2)
x4 = np.ones_like(X1)
X5 = np.random.randn(X1.shape[0])

In [84]:
def neural_network(X):
    HL1=np.array([0.25,0.37])
    HL2=np.array([-8,14])
    OutputLayer=np.array([4,9])
    resul=np.array([np.dot(X,HL1),np.dot(X,HL2)])
    resultado=np.argmax(resul)
    resultado+=1
    return resultado 
print(neural_network(X1))
print(neural_network(X2))
print(neural_network(X3))
print(neural_network(x4))
print(neural_network(X5))

2
2
1
2
2


## Ejercicio 11: Correlacion cruzada
El primer paso es definir la función G que define el "filtro" a aplicar, para este caso consiste simplemente en un vector con 3 elementos donde cada elemento corresponde a 1/3, luego debemos aplicar el producto punto sobre cada punto de la función o datos originales(en este ejemplo llamados x) a traves aplicar el producto punto en cada elemento "corriendolo" de uno en uno

In [85]:
ruido = 0.1*np.random.randn(15) #el ruido comunmente se debe a aleatoriedad o captura no exacta de info.
x = np.linspace(0,2*np.pi,15) + ruido
x = np.sin(x)

filtro = np.array([1/3,1/3,1/3])

## tu codigo aqui (~ 3 linea de codigo)
xprima = x.copy()
for i in range(1,len(x)-1):
    xprima[i] = np.inner(xprima[i-1:i+2], filtro)
    
print(xprima)

[ 0.03277664  0.34576823  0.70390403  0.88267186  0.91433754  0.71524055
  0.33660938 -0.10638269 -0.51481228 -0.77111216 -0.91573129 -0.87536539
 -0.69502195 -0.43040878 -0.10280262]


## Ejercicio 12: Vectores Booleanos
Dado el vector x, usar operadores lógicos sobre vectores y acceso a  elementos usando vectores booleanos , escribir un programa que calcule eun nuevo vector z conteniendo el valor absoluto de el vector x.

**nota** No se puede usar np.abs() ni ciclos

**tip** usar un vector booleano para saber que elementos son negativos y deben ser multiplicados por -1

In [93]:
x = np.linspace(-2,2,9)

## tu codigo aqui (~ 4 linea de codigo)
y=x[x<0]
y*=-1
z=np.hstack((y,x[x>=0]))
print(z)

[2.  1.5 1.  0.5 0.  0.5 1.  1.5 2. ]


## Ejercicio 13: Implementar funcion booleana
Implementar la función:
$$h(x) = \begin{cases}0 & x< 0\\1 & 0<=x <=1\\0 & x> 1\end{cases}$$

Esta debe funcionar para vectores de cualquier tamaño x:

def h(x):

    ...

**nota** debe ser implementada sin ciclos o ifs

In [100]:
def h(x):
    ## tu codigo aqui (~ 3 linea de codigo)
    aux=[x < 0, (x >= 0) * (x <= 1), x > 1]
    condicion=[0,1,0]
    h=np.select(aux,condicion)
    return h

x = np.array([0.1,-2,0.5,5])
print(h(x))

[1 0 1 0]


## Ejercicio 14 Implementacion de otra funcion booleana
Usando select implementar una función k(x) con la siguiente definición:
$$k(x) = \begin{cases}-x & x< 0\\x^{3}  &0<=x<1\\x^{2}  &1<=x<2\\4  &otherwise\end{cases}$$

In [101]:
def k(x):
    condiciones=[x<0,(x>=0)*(x<1),(x>=1)*(x<2)]
    resultados = [-x,x**3,x**2]
    k=np.select(condiciones,resultados,4)
    return k
print(k(x))

[1.00e-03 2.00e+00 1.25e-01 4.00e+00]


## Ejercicio 15: Uso de Piecewise
Investigar piecewise y:
*  Usarlo para implementar la función anterior de manera eficiente
*  Usar piscewise para implementar la función:

$$m(x) = \begin{cases}e^{2x} & x< 0\\1  &0<=x<1\\e^{1-x}  &x<=1\\\end{cases}$$

Nuevamente, sin utilizar ciclos ni ifs

In [104]:
# Funcion K usando Piecewise
def k_piecewise(x):
    condiciones=[x<0,(x>=0)*(x<1),(x>=1)*(x<2),x>=2]
    resultados = [lambda x: -x,lambda x: x**3,lambda x: x**2,4]
    k=np.piecewise(x,condiciones,resultados)
    return k
print(k_piecewise(x))

[1.00e-03 2.00e+00 1.25e-01 4.00e+00]


In [107]:
# Funcion M usando Piecewise
def m(x):
    condicionales=[x<0,(x>=0)*(x<1),x>=1]
    resultados=[lambda x: np.power(np.e,2*x),1,lambda x: np.power(np.e,1-x)]
    m=np.piecewise(x,condicionales,resultados)
    return m
print(x)
print(m(x))

[ 0.1 -2.   0.5  5. ]
[1.         0.01831564 1.         0.01831564]


#### Investigar

* Proyección vectorial
    * Definir una función para calculo en numpy
    * interpretación
    * aplicación o caso de uso en DS u otras ciencias de tu interés: solo se necesita nombrar el caso de uso, no desarrollarlo o programarlo, tip: Hay un algoritmo de ML cuyo nombre puede ser  útil.
* Producto cruz
    * calculo en numpy
    * interpretación
    * aplicación o caso de uso en DS u otras ciencias de tu interés: solo se necesita nombrar el caso de uso, no desarrollarlo o programarlo

### Proyección Vectorial
#### Interpretación: 
Gráficamente la proyección vectorial se puede representar como lo siguiente:

Tenemos los siguientes vectores u y v, que forman un ángulo alfa:

<img src="https://ekuatio.com/wp-content/uploads/proyeccion-vectores-1.png">

Vamos a representar gráficamente la proyección del vector u sobre el vector v (que como veremos más adelante, no es igual a la proyección del vector v sobre u). Para ello, desde el extremo de u, trazamos una recta perpendicular al vector v:

<img src="https://ekuatio.com/wp-content/uploads/proyeccion-vectores-2.png">

Ahora, sobre el vector v, dibujamos un vector desde el origen de ambos vectores hasta el punto donde se cortan la recta perpendicular y el vector v. El vector resultante (de color verde) es el vector proyección de u en v:
<img src="https://ekuatio.com/wp-content/uploads/proyeccion-vectores-3.png">

Con un angulo obtuso el procedimiento es siempre el mismo: Desde el extremo del vector que queremos obtener la proyección trazamos una perpendicular del vector sobre el que queremos proyectarlo. Luego, en ese mismo vector, trazamos un nuevo vector desde el origen hasta el punto donde se corta con la recta perpendicular.

De esta forma, la proyección del vector u sobre v es:

<img src="https://ekuatio.com/wp-content/uploads/proyeccion-vectores-7.png">

#### Funcion calculada usando numpy

In [3]:
def vecProj(u,v): #Funcion de proyeccion de U sobre V
    v_norm = np.sqrt(sum(v**2)) #Encuentra la norma del vector v
    proj_of_u_on_v = (np.dot(u, v)/np.power(v_norm,2))*v
    return proj_of_u_on_v

u = np.array([1, 2, 3])   # vector u 
v = np.array([5, 6, 2])   # vector v

print(vecProj(u,v))

[1.76923077 2.12307692 0.70769231]


#### Aplicaciones en DS
La proyección es un concepto muy útil y utilizado por una de las famosas técnicas de reducción de dimensionalidad conocida como PCA (análisis de componentes principales). Cuando los datos residen en dimensiones más altas para verlos, tenemos que empujarlos en dimensiones más bajas, que es una de las partes más importantes de cualquier técnica de reducción de dimensionalidad donde esto juega un papel crucial.

##### E-grafia
* https://ekuatio.com/proyeccion-de-un-vector-sobre-otro-vector-ejercicios-resueltos/
* https://www.geeksforgeeks.org/vector-projection-using-python/
* https://medium.com/@swastiknayak76/linear-algebra-for-data-science-and-machine-learning-caa886e38a84

### Producto Cruz
#### Interpretacion:
Es una operacion entre dos vectores que da como resultado un vector perpendicular a los vectores que se multiplican, y por lo tanto normal al plano que los contiene. Geometricamente se puede representar de la siguiente forma:
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Cross_product_parallelogram.svg/1024px-Cross_product_parallelogram.svg.png">
<img src="https://upload.wikimedia.org/wikipedia/commons/7/71/Producto_vectorial_2.png">

La magnitud de este nuevo vector representa el area formada por el paralelogramos de los 2 vectores iniciales.

#### Funcion en numpy
numpy ya cuenta con una funcion para calcular el producto cruz entre dos vectores, la funcion se llama np.cross(a,b) recibe 2 vectores y el resultado es un np.array con el vector resultante de la operacion, a continuacion un ejemplo de su uso:

In [4]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

#### Aplicaciones en DS
Es utilizado para realizar cálculos y simulaciones de experimentos fisicos donde se recopilan gran cantidad de datos y se necesita realizar el cálculo de dicho vector

#### E-grafia
* https://www.geogebra.org/m/B6Uz5yWf