In [6]:
import sys
!conda install --yes --prefix {sys.prefix} numpy

# ! ejecuta un comando del sistema desde el notebook, el comando ejecutado fue:
print("Comando ejecutado:conda install --yes --prefix {"+sys.prefix+"} numpy")

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.2                |           py37_0         2.8 MB
    ------------------------------------------------------------
                                           Total:         2.8 MB

The following packages will be UPDATED:

  conda                                       4.7.12-py37_0 --> 4.8.2-py37_0




conda-4.8.2          | 2.8 MB    |            |   0% 
conda-4.8.2          | 2.8 MB    |            |   1% 
conda-4.8.2          | 2.8 MB    | 8          |   9% 
conda-4.8.2          | 2.8 MB    | ###4       |  34% 
conda-4.8.2          | 2.8 MB    | #####8     |  59% 
conda-4.8.2          | 2.8 MB    | ########4  |  84% 
conda-4.8.2          | 2.8 MB    | ########## | 100% 
Comando ej


InvalidArchiveError("Error with archive C:\\Users\\Sebastián\\.conda\\pkgs\\conda-4.8.2-py37_0uksfvoii\\info-conda-4.8.2-py37_0.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to open 'C:\\Users\\Sebastián\\.conda\\pkgs\\conda-4.8.2-py37_0uksfvoii\\info-conda-4.8.2-py37_0.tar.zst'")



In [2]:
import numpy as np

# Ejercicio 1

En data science y programación científica es común necesitar vectores con valores dentro de cierto intervalo, pero con sub-intervalos internos con diference espaciamiento ,por ejemplo:

[0. , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.7 , 0.8 , 0.9 , 1. ]

El primer sub-intervalo incrementa de 0.1 en 0.1 , el segundo de 0.01 en 0.01 , y el tercero de 0.1 en 0.1 nuevamente.

Usando unicamente NumPy crea un vector de este tipo con el nombre xs .

nota: no es permitido usar ciclos, debe realizarse con operaciones "vectorizadas" de numpy

In [16]:
np.hstack(
(np.arange(0,0.6,0.1), 
np.arange(0.51, 0.6, 0.01), 
np.arange(0.6, 1.01, 0.1)))

array([0.  , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.7 , 0.8 , 0.9 , 1.  ])

# Ejercicio 2 

En este caso usamos un ciclo para ejemplificar pero ya hemos mencionado que debemos evitarlos siempre que sea posible y usar operaciones "vectorizadas" ya que es mucho mas rápido al utilizar código pre-compilado de C, en este ejercicio debemos remplazar el calculo de xs para hacerlo de manera "vectorizada" y eliminar el ciclo for.

tip: usar slicing

In [17]:
# tu codigo aqui (~ 5 lineas de codigo):
ruido = 0.1*np.random.randn(15) #el ruido comunmente se debe a aleatoriedad o captura no exacta de info.
x = np.linspace(0,2*np.pi,15) + ruido
x = np.sin(x)

xs =  x.copy()
# codigo nuevo 
xl = np.hstack((x[1:len(x)], np.nan))
xr = np.hstack((np.nan, x[:len(x)-1]))
xs = (x + xr + xl) / 3
xs[0] = x[0]
xs[len(xs)-1] = x[len(x)-1]

    
print(x)
print(xs)

[ 0.06053548  0.48475466  0.72664295  0.99989542  0.93862179  0.80873603
  0.28004454  0.13580465 -0.55702454 -0.71042607 -0.95290787 -0.97802247
 -0.74798674 -0.28454414  0.05348116]
[ 0.06053548  0.4239777   0.73709768  0.88838672  0.91575108  0.67580079
  0.40819507 -0.04705845 -0.37721532 -0.74011949 -0.88045214 -0.89297236
 -0.67018445 -0.32634991  0.05348116]


# Ejercicio 3

Para calcular la información de una distribución de probabilidad necesitamos calcular el producto entre la información de cada posible x y su probabilidad , cada uno de estos elementos nos indica cuanta incerteza aporta cada x a la entropía de la distribución. Crea una función que calcule esto, debe recibir un vector representando a la dist. de probabilidad y devoler otro vector con el termino de entropía para cada x. Por ejemplo:

calcular_entropia([0.25,0.75])

Debe resultar en :

[0.5 , 0.31127812]

Nota: la entropía es la suma sobre estos valores, en este caso no calculamos la entropía,unicamente los termimos de su sumatoria. La entropía es:

𝑆=−∑𝑖𝑛𝑃(𝑥𝑖)𝑙𝑜𝑔2𝑃(𝑥𝑖)

In [20]:
# tu codigo aqui (~ 4 lineas de codigo)  

def entropia(n):
    return -1*(n*np.log2(n))

entropia([0.25,0.75])


array([0.5       , 0.31127812])

# Ejercicio 4

Se ha determinado también que hay costos asociados a la comunicación y relación con los clientes(llamadas,mensajes electrónicos,etc) y que estos también tienen alta correlación con el monto que estos gastan en su primer més siguiendo el modelo:
𝑐(𝑥)=(𝑥2+𝑥+𝑙𝑜𝑔(0.0001𝑥)−0.54𝑥⎯⎯⎯⎯⎯⎯⎯⎯⎯√)/100
 
Cree una función para calcular este modelo sobre valores de de gasto de nuevos clientes , y luego cree una función ganancia_neta(x,g,c) donde:

x = vector conteniendo los valores de gasto del primer mes para nuevos clientes.
g = función que estima la ganancia en función de x
c = función que estima el costo en función de x
La función realiza el calculo simple g(x) - c(x) , ya que es posible que los modelos cambien en el tiempo es común recibir como parámetro el modelo o modelos hijos de un modelo mas grande , en este caso eso se logra recibiendo como parámetro las funciones de ganancia y costo.

In [30]:
# Codigo del ejemplo anterior
def g(x):
    ganancia = (np.power(x,3) + 2.0*(np.power(x,2.0))+np.exp(0.0001*x) - np.sqrt(2.0*x))/50
    
    return ganancia
    
gastos = np.array([100,50,25])
ganancia = g(gastos)

print("Ganancias",ganancia)
# Fin del codigo del ejemplo anterior 

def c(x):
    return (x**2+x+np.log10(0.0001*x))-np.sqrt(0.54*x)/100
def gan_netadex(x,g,c):
    return g(x)-c(x)

ganancia = gan_netadex(gastos,g,c)

ganancia

Ganancias [20399.73735829  2599.82010025   337.37862871]


array([10301.81084298,    52.17309177,  -309.98256896])

# Ejercicio 5

Usando argmax crear una función mode(x) para calcular la moda de un vector x , esta función debe devolver una tupla de 2 elementos de la forma:

(valor,conteo)

tip investigar y auxiliarse de otras funciones de numpy y np.argmax, no olvidar trabajar todo vectorizado, sin ciclos.

In [ ]:
def mode(x):
    ## tu codigo aqui (~ 3 lineas de codigo):
    
    
print(mode(x))

# Ejercicio 6

Crear una función para calcular la entropía de una distribución de probabilidad representada como un vector.
𝑆=−∑𝑖𝑛𝑃(𝑥𝑖)𝑙𝑜𝑔2𝑃(𝑥𝑖)
 
Nota: a diferencia del ejercicio anterior donde solo calculamos los términos de la entropía, en este caso si calculamos el valor completo de la entropía, que como mencionamos es una medida de incerteza en una distribución de probabilidad.

recordatorio: no usar ciclos solo operaciones vectorizadas.

In [31]:
# tu codigo aqui (~ 3 lineas de codigo)
def entropia(n):
    return -np.sum(n*np.log2(n)) 

entropia([0.25,0.75])

0.8112781244591328

# Ejercicio 7

En ML usamos la entropía cruzada como una forma de medir que tan bueno es un modelo de variables discretas a través de comparar la distribución de probabilidad que el modelo produce o predice, vs la distribución de probabilidad real dada por los datos de entrenamiento.

Podemos ver el siguiente ejemplo que define la forma en que se calcula la entropía cruzada y nos muestra un caso específico:


En este caso interpretamos así: El problema consiste en un modelo o algoritmo de ML que debe producir un vector de 3 elementos indicando la probabilidad de que ciertos datos X pertenezcan a una de 3 categorías.

El modelo de ML produce un vector que indica que estima un 70% de probabilidad de que se trate de la categoría 0, 20% de probabilidad de que se trate de la categoría 1 y 10% de que se trate de la categoría 2.
Los datos reales nos dicen que se trataba de un caso donde con total certeza se sabe que se trata de la categoría 0
La entropía cruzada(a calcular en el ejercicio) nos indica que tan buena es la estimación del modelo, una EC de 0 es un modelo perfecto(en este caso un modelo que predice 100% de prob para la clase 0)
Nota

Aun que para calcular la entropía usamos logaritmos en base 2, en ML para calcular la entropía cruzada se usa logaritmo natural ya que con este se cumple el proposito estimar que tanto se alejan las predicciones del modelo de ML de los datos reales y es comunmente mas rápido de calcular en la computadora.

Ya que estamos trabajando con vectores que representan distribuciones de probabilidad , podemos toparnos con lo que se conoce como : sparse vectors(vectores donde la mayoría de elementos son 0), esto puede producir problemas ya que le logaritmo de 0 no esta definido, tu solución debe tomar en cuenta esto y evitar que devuelva "nan"

In [36]:
def cross_entropy(Y,Y_hat):
    ##tu codigo aqui (~ 1 lineas de codigo)
    return np.sum(-((Y*np.log(Y_hat))+((1-Y)*np.log(1- Y_hat))))
    

y  = np.array([1.0,0,0])
y_hat = np.array([0.7,0.2,0.1])

cross_entropy(y,y_hat)

0.6851790109107685

# Ejercicio 8

Crear una función que reciba como parámetro un vector x y calcule su magnitud o norma(euclidiana o L2) ,luego usarla para evaluar 2 vectores que representan los errores generados por 2 modelos de machine learning y concluir cual de los 2 modelos es mejor.

In [37]:
def magnitud(x):
    ## tu codigo aqui (~ 1 linea de codigo)
    return np.sqrt(np.inner(x,x))

errores_modelo1 = np.array([1,2,1,2])
errores_modelo2 = np.array([0,1,1,2])

print(magnitud(errores_modelo1))
print(magnitud(errores_modelo2))

3.1622776601683795
2.449489742783178


# Ejercicio 9

Usando la función del ejercicio anterior, crea otra función normalizar(x) que reciba de parámetro un vector x aplique normalización sobre este, el resultado debe ser un nuevo vector del tamaño de x cuya magnitud es igual a 1.0

In [38]:
def normalizar(x):
    ## tu codigo aqui (~ 3 linea de codigo)
    return x/magnitud(x)
    

print(magnitud(normalizar(errores_modelo1)))
print(normalizar(errores_modelo2))

1.0
[0.         0.40824829 0.40824829 0.81649658]


# Ejercicio 10

la correlación cruzada es una medida de similitud entre 2 funciones como resultado de "desplazar" una sobre la otra, comunmente es usada para encontrar características relevantes en una función desconocida o no controlada.

En procesamiento de señales por ejemplo es usada para buscar y/o filtrar en una señal que varia en el tiempo cierta caracaterística de interés. Aveces es llamada también "sliding dot product" consiste en aplicar en cada punto de una función F el producto punto con cierta función G(comunmente mas corta) y luego "deslizar" G a un nuevo punto de la función, el resultado es una nueva función H que se interpreta como :cuanto se parece en cada punto la función F a la característica G.


En este ejercicio usamos correlación cruzada para calcular las medias moviles promediando 3 puntos que ya vimos en otro ejemplo:

El primer paso es definir la función G que define el "filtro" a aplicar, para este caso consiste simplemente en un vector con 3 elementos donde cada elemento corresponde a 1/3, luego debemos aplicar el producto punto sobre cada punto de la función o datos originales(en este ejemplo llamados x) a traves aplicar el producto punto en cada elemento "corriendolo" de uno en uno

In [39]:
ruido = 0.1*np.random.randn(15) #el ruido comunmente se debe a aleatoriedad o captura no exacta de info.
x = np.linspace(0,2*np.pi,15) + ruido
x = np.sin(x)

filtro = np.array([1/3,1/3,1/3])

## tu codigo aqui (~ 3 linea de codigo)
xs = x.copy()
for i in range(1,len(x)-1):
    xs[i] = np.inner(xs[i-1:i+2], filtro)
    
xs

array([-0.09340523,  0.36537997,  0.66795243,  0.87604944,  0.86382294,
        0.65635505,  0.33281523, -0.04440578, -0.4358289 , -0.74404771,
       -0.89146591, -0.89850306, -0.78904815, -0.51237772, -0.10899953])

# Ejercicio 11

dado el vector x, usar operadores lógicos sobre vectores y acceso a elementos usando vectores booleanos , escribir un programa que calcule eun nuevo vector z conteniendo el valor absoluto de el vector x.

nota No se puede usar np.abs() ni ciclos

tip usar un vector booleano para saber que elementos son negativos y deben ser multiplicados por -1

In [48]:
x = np.linspace(-2,2,9)


## tu codigo aqui (~ 4 linea de codigo)
def mipropioabs(x):
    v = x.copy()
    v[v<0] = -v[v<0]
    return v

mipropioabs(x)

array([2. , 1.5, 1. , 0.5, 0. , 0.5, 1. , 1.5, 2. ])

# Ejercicio 12

Implementar la función:

 
Esta debe funcionar para vectores de cualquier tamaño x:

def h(x):

...
nota debe ser implementada sin ciclos o ifs

In [3]:
def h(x):
    ## tu codigo aqui (~ 3 linea de codigo)
    a = [x < 0, (x >= 0) * (x <= 1), x > 1]
    b = [0,1,0]
    c = np.select(a,b)
    ##
    return c

x = np.array([0.1,-2,0.5,5])
print(h(x))

[1 0 1 0]


# Ejercicio 13

Usando select implementar una función k(x) con la siguiente definición:

Select y performance
Aun que select es muy conveniente y útil , no es la opción mas eficiente esto debido a que evalua todas las condiciones y todos los resultados, en programación en general buscamos escribir los programas de la manera mas eficiente posible y evitar calculos innecesarios, esto se vuelve vital en ciencia de datos cuando procesamos grandes volúmenes de información, por eso NumPy nos provee la alternativa a select llamada piecewise que funciona de manera similar .

Este funciona similar a select pero en vez de calcular todos los posibles resultados, calcula solo aquellos para los que la condición es True e ignora los False,sintácticamente piecewise requiere que los "resultados" sesan calcuados usando una lista de funciones por lo cual todos los resultados deben estar contenidos en una función y el objeto función ser enviado a piecewise (si la función solo se utiliza una vez para este propósito, se puede usar funciones anónimas o lambda).

In [68]:
x = np.linspace(1,10,10)
condiciones = [x<0,(0<=x)*(x<1),(1<=x)*(x<2), x>=2]
resultados = [-x,x**3,x**2,4]
k = np.select(condiciones,resultados,1)

print(x)
print(k)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 4. 4. 4. 4. 4. 4. 4. 4. 4.]


# Ejercicio 14

Investigar piecewise y:

Usarlo para implementar la función anterior de manera eficiente
Usar piscewise para implementar la función:

 
Nuevamente, sin utilizar ciclos ni ifs

In [65]:
def m(x):
    return np.piecewise(x, [x < 0, (x >= 0)*(x < 1), x >=1], [lambda x: np.exp(2*x), 1, lambda x: np.exp(1-x)])

x =np.arange(-1,0.52,30.45)
m(x)

array([0.13533528])

# Investigar

-Proyección vectorial

-Definir una función para calculo en numpy

-interpretación

-aplicación o caso de uso en DS u otras ciencias de tu interés: solo se necesita nombrar el caso de uso, no desarrollarlo o programarlo, tip: Hay un algoritmo de ML cuyo nombre puede ser útil.

-Producto cruz

-calculo en numpy

-interpretación

-aplicación o caso de uso en DS u otras ciencias de tu interés: solo se necesita nombrar el caso de uso, no desarrollarlo o programarlo